# ##############################################################################
# Alacritty color configurations
# ##############################################################################

colors:
  primary:
    background: '0x002b36'
    foreground: '0x657b83'
    dim_foreground: '0x657b83'
    bright_foreground: '0x657b83'
  cursor:
    text: '0x002b36'
    cursor: '0xdc322f'
  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'
  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'
  indexed_colors: []

# ##############################################################################
# Alacritty setup configurations
# ##############################################################################

env:
  TERM: xterm-256color
shell:
  program: /bin/bash
  args:
    - --login
window:
  decorations: none
  padding:
    x: 8
    y: 8
font:
  normal:
    family: "Fira Code"
    style: Regular
  bold:
    family: "Fira Code"
    style: Bold
  italic:
    family: "Fira Code"
    style: Italic
  size: 12.0
scrolling:
  auto_scroll: true
selection:
  save_to_clipboard: true
mouse:
  hide_when_typing: true
  url:
    launcher:
      program: open # Linux alias: xdg-open
      args: []
    modifiers: None

# ##############################################################################
# Alacritty keybindings
# ##############################################################################

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
key_bindings:
  - { key: 0x40, mods: Super, chars: "\x00"} # @
  - { key: A, mods: Super, chars: "\x01"}
  - { key: B, mods: Super, chars: "\x02"}
  - { key: C, mods: Super, chars: "\x03"}
  - { key: D, mods: Super, chars: "\x04"}
  - { key: E, mods: Super, chars: "\x05"}
  - { key: F, mods: Super, chars: "\x06"}
  - { key: G, mods: Super, chars: "\x07"}
  - { key: H, mods: Super, chars: "\x08"}
  - { key: I, mods: Super, chars: "\x09"}
  - { key: J, mods: Super, chars: "\x0A"}
  - { key: K, mods: Super, chars: "\x0B"}
  - { key: L, mods: Super, chars: "\x0C"}
  - { key: M, mods: Super, chars: "\x0D"}
  - { key: N, mods: Super, chars: "\x0E"}
  - { key: O, mods: Super, chars: "\x0F"}
  - { key: P, mods: Super, chars: "\x10"}
  - { key: Q, mods: Super, chars: "\x11"}
  - { key: R, mods: Super, chars: "\x12"}
  - { key: S, mods: Super, chars: "\x13"}
  - { key: T, mods: Super, chars: "\x14"}
  - { key: U, mods: Super, chars: "\x15"}
  - { key: V, mods: Super, chars: "\x16"}
  - { key: W, mods: Super, chars: "\x17"}
  - { key: X, mods: Super, chars: "\x18"}
  - { key: Y, mods: Super, chars: "\x19"}
  - { key: Z, mods: Super, chars: "\x1A"}
  - { key: 0x5b, mods: Super, chars: "\x1B"} # [
  - { key: 0x5c, mods: Super, chars: "\x1C"} # \
  - { key: 0x5d, mods: Super, chars: "\x1D"} # ]
  - { key: 0x5e, mods: Super, chars: "\x1E"} # ^
  - { key: 0x5f, mods: Super, chars: "\x1F"} # _