# Set the proper terminal colors
env:
  TERM: xterm-256color

# Set to bash and login shell
shell:
  program: /bin/bash
  args:
    - --login

# Full window decorations
window:
  decorations: none
  padding:
    x: 8
    y: 8

# Use Fira Code font
font:
  normal:
    family: "Fira Code"
    style: Regular
  bold:
    family: "Fira Code"
    style: Bold
  italic:
    family: "Fira Code"
    style: Italic
  size: 12.0

# Shades of Purple based colorscheme
colors:
  primary:
    background: '0x1e1d40'
    foreground: '0xfcfcfc'
    dim_foreground: '0xfcfcfc'
    bright_foreground: '0xffffff'
  cursor:
    text: '0x000000'
    cursor: '0xfad000'
  normal:
    black:   '0x000000'
    red:     '0xd90429'
    green:   '0x3ad900'
    yellow:  '0xfad000'
    blue:    '0x6943ff'
    magenta: '0xff2c70'
    cyan:    '0x80fcff'
    white:   '0xc7c7c7'
  bright:
    black:   '0x808080'
    red:     '0xff0000'
    green:   '0x33ff00'
    yellow:  '0xffff00'
    blue:    '0x0066ff'
    magenta: '0xcc00ff'
    cyan:    '0x00ffff'
    white:   '0xffffff'
  indexed_colors: []

# Miscellaneous personal preferences
scrolling:
  auto_scroll: true
selection:
  save_to_clipboard: true
mouse:
  hide_when_typing: true
  url:
    launcher:
      program: open # Linux alias: xdg-open
      args: []
    modifiers: None

# Mouse event bindings
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

# Keyboard event bindings
key_bindings:
  - { key: 0x40, mods: Super, chars: "\x00"} # @
  - { key: A, mods: Super, chars: "\x01"}
  - { key: B, mods: Super, chars: "\x02"}
  - { key: C, mods: Super, chars: "\x03"}
  - { key: D, mods: Super, chars: "\x04"}
  - { key: E, mods: Super, chars: "\x05"}
  - { key: F, mods: Super, chars: "\x06"}
  - { key: G, mods: Super, chars: "\x07"}
  - { key: H, mods: Super, chars: "\x08"}
  - { key: I, mods: Super, chars: "\x09"}
  - { key: J, mods: Super, chars: "\x0A"}
  - { key: K, mods: Super, chars: "\x0B"}
  - { key: L, mods: Super, chars: "\x0C"}
  - { key: M, mods: Super, chars: "\x0D"}
  - { key: N, mods: Super, chars: "\x0E"}
  - { key: O, mods: Super, chars: "\x0F"}
  - { key: P, mods: Super, chars: "\x10"}
  - { key: Q, mods: Super, chars: "\x11"}
  - { key: R, mods: Super, chars: "\x12"}
  - { key: S, mods: Super, chars: "\x13"}
  - { key: T, mods: Super, chars: "\x14"}
  - { key: U, mods: Super, chars: "\x15"}
  - { key: V, mods: Super, chars: "\x16"}
  - { key: W, mods: Super, chars: "\x17"}
  - { key: X, mods: Super, chars: "\x18"}
  - { key: Y, mods: Super, chars: "\x19"}
  - { key: Z, mods: Super, chars: "\x1A"}
  - { key: 0x5b, mods: Super, chars: "\x1B"} # [
  - { key: 0x5c, mods: Super, chars: "\x1C"} # \
  - { key: 0x5d, mods: Super, chars: "\x1D"} # ]
  - { key: 0x5e, mods: Super, chars: "\x1E"} # ^
  - { key: 0x5f, mods: Super, chars: "\x1F"} # _