#!/bin/bash

# ##############################################################################
# Environment variables for MacOS and Linux
# ##############################################################################

# Check platform
[[ "$(uname -s)" == "Darwin" ]] && macos="true" || linux="true";

# Common variables
export DOTFILES="$HOME/Projects/dotfiles";
export LANG="en_IE.UTF-8";
export LANGUAGE="en_IE.UTF-8";
export LC_ALL="en_IE.UTF-8";
export PAGER="less";
export MANPAGER="most";
export NVM_DIR="$HOME/.nvm";

# Append program paths
export PATH="$PATH:/usr/local/sbin";
export PATH="$PATH:/usr/local/bin";
export PATH="$PATH:/usr/bin";
export PATH="$PATH:/usr/sbin";
export PATH="$PATH:/bin";
export PATH="$PATH:/sbin";
export PATH="$PATH:$HOME/.local/share/gem/ruby/3.0.0/bin";

# MacOS specific variables
[[ "$macos" == "true" ]] && export BASH_SILENCE_DEPRECATION_WARNING=1;
[[ "$macos" == "true" ]] && export GEM_HOME="$HOME/.gem";
[[ "$macos" == "true" ]] && export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin";

# Linux specific variables
[[ "$linux" == "true" ]] && export GTK_THEME=Adwaita:dark
[[ "$linux" == "true" ]] && export QT_QPA_PLATFORMTHEME=qt5ct
