#!/bin/bash

# ##############################################################################
# Bash environment variables for MacOS and Linux
# ##############################################################################

[[ "$(uname -s)" == "Darwin" ]] && macos="true" || linux="true";

export DOTFILES="$HOME/Projects/dotfiles";
export LANG="en_IE.UTF-8";
export LANGUAGE="en_IE.UTF-8";
export LC_ALL="en_IE.UTF-8";
export PAGER="less";
export MANPAGER="most";
export GREP_COLOR=always;
export CLICOLOR_FORCE=true;
export NVM_DIR="$HOME/.nvm";
export GEM_HOME="$HOME/.gem";

export PATH="$PATH:/usr/local/sbin";
export PATH="$PATH:/usr/local/bin";
export PATH="$PATH:/usr/bin";
export PATH="$PATH:/usr/sbin";
export PATH="$PATH:/bin";
export PATH="$PATH:/sbin";
export PATH="$PATH:$HOME/.local/share/gem/ruby/3.0.0/bin";
export PATH="$PATH:$HOME/.config/composer/vendor/bin";
export PATH="$PATH:$HOME/.local/bin";

[[ "$macos" == "true" ]] && export BASH_SILENCE_DEPRECATION_WARNING=1;
[[ "$macos" == "true" ]] && export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin";
[[ "$linux" == "true" ]] && export GTK_THEME=Yaru:dark
[[ "$linux" == "true" ]] && export QT_QPA_PLATFORMTHEME=qt5ct
