# ##############################################################################
# Starship configuration
# ##############################################################################

format = "$username$sudo$directory$git_branch$git_status$git_state$package$cmd_duration[\\$](green bold) "
scan_timeout = 10
add_newline = false

[username]
style_user = "purple bold"
style_root = "bg:purple fg:black bold"
format = "[$user]($style) "
show_always = true

[directory]
style = "cyan bold"
read_only_style = "cyan bold"
format = "in [$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = true

[git_branch]
style = "154 bold"
format = "on [$symbol$branch]($style) "
symbol = " "

[git_status]
style = "red bold"
format = '([\[$all_status$ahead_behind\]]($style) )'

[git_state]
style = "203 bold"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[package]
style = "208 bold"
format = "is [$symbol$version]($style) "
symbol = "📦 "
display_private = true

[cmd_duration]
style = "yellow bold"
format = "took [$duration]($style) "
show_milliseconds = true
min_time = 1

[sudo]
style = 'green bold'
symbol = '🧙 '
format = '[as $symbol]($style)'
disabled = false