#!/bin/bash

# Start pulseaudio daemon
pulseaudio --daemonize;

# Custom display-settings script using xrandr
bash ~/dotfiles/scripts/display-settings.sh home;

# Set the solid background color
xsetroot -solid '#2d2b55';

# Set the background image
feh --no-fehbg --bg-fill ~/Pictures/minimal-red-hills_3840x2160.jpg

# Set custom keyboard mappings
bash ~/dotfiles/scripts/keyboard-settings.sh;

# Set custom pointer settings
bash ~/dotfiles/scripts/pointer-settings.sh;

# Auto-start applications
#bash megasync &;
#bash xterm &;

# Start i3-gaps window manager
exec i3;
