#!/bin/bash

# ##############################################################################
# Yabai configuration
# ##############################################################################

yabai -m config window_placement second_child;
yabai -m config window_topmost on;
yabai -m config auto_balance off;
yabai -m config layout bsp;
yabai -m config top_padding 16;
yabai -m config bottom_padding 16;
yabai -m config left_padding 16;
yabai -m config right_padding 16;
yabai -m config window_gap 16;
yabai -m config mouse_modifier fn;
yabai -m config mouse_action1 move;
yabai -m config mouse_action2 resize;
yabai -m config mouse_follows_focus off;
yabai -m config focus_follows_mouse off;
yabai -m config window_opacity on;
yabai -m config active_window_opacity 1.00;
yabai -m config normal_window_opacity 0.90;
yabai -m config window_opacity_duration 0.0;
yabai -m config window_shadow on;
yabai -m config window_border off;
yabai -m config status_bar off;

yabai -m rule --add app="^.*$" manage=off;
yabai -m rule --add app="^Finder$" title!="^(Co(py|nnect)|Move|.*Info|Pref|Bin|\s*)$" manage=on;
yabai -m rule --add app="^Safari$" title!="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance|\s*)$" manage=on;
yabai -m rule --add app="^(Firefox.*)$" title!="^(Opening.*|Open File)$" manage=on;
yabai -m rule --add app="^Mail$" title!="^(Signatures|Accounts|Junk Mail|Fonts & Colours|Viewing|Composing|Signatures|Rules|\s*)$" manage=on;
yabai -m rule --add app="^(Rider|WebStorm|JetBrains.*|Android Studio)$" title!="^(Welcome to.*|Preferences|\s*)$" manage=on;
yabai -m rule --add app="^Unity$" title!="^()$" manage=on;
yabai -m rule --add app="^Preview$" title="^(.*.pdf.*)$" manage=on;
yabai -m rule --add app="^(GIMP.*)$" title="^(GNU Image Manipulation Program|.*– GIMP)$" manage=on;
yabai -m rule --add app="^XD$" title!="^(Adobe XD|\s*)$" manage=on;
yabai -m rule --add app="^Code$" title!="^\s*$" manage=on;
yabai -m rule --add app="^kitty$" manage=on;
yabai -m rule --add app="^Spotify$" manage=on;
yabai -m rule --add app="^Calendar$" manage=on;
yabai -m rule --add app="^Google Chrome|Chromium$" title!="^\s*$" manage=on;
yabai -m rule --add app="^Microsoft Edge$" title!="^\s*$" manage=on;
yabai -m rule --add app="^Postman$" manage=on;
yabai -m rule --add app="^MacPass$" title!="^(Open)$" manage=on;
yabai -m rule --add app="^FileZilla$" title!="^(Check for Updates|\s*)" manage=on;
yabai -m rule --add app="^AppCleaner$" manage=on;
yabai -m rule --add app="^WhatsApp$" manage=on;
yabai -m rule --add app="^Slack$" manage=on;
yabai -m rule --add app="^Skype.*$" manage=on;
yabai -m rule --add app="^Microsoft Teams$" manage=on;
yabai -m rule --add app="^Microsoft (Word|Excel|PowerPoint|OneNote|Outlook)$" title!="^Microsoft (Word|Excel|PowerPoint|OneNote|Outlook)$" manage=on;
yabai -m rule --add app="^LibreOffice$" manage=on;