#!/bin/bash

# ##############################################################################
# Yabai setup configurations
# ##############################################################################

yabai -m config window_placement second_child;
yabai -m config window_topmost on;
yabai -m config auto_balance off;
yabai -m config layout bsp;
yabai -m config top_padding 16;
yabai -m config bottom_padding 16;
yabai -m config left_padding 16;
yabai -m config right_padding 16;
yabai -m config window_gap 16;
yabai -m config mouse_modifier fn;
yabai -m config mouse_action1 move;
yabai -m config mouse_action2 resize;
yabai -m config mouse_follows_focus off;
yabai -m config focus_follows_mouse off;
yabai -m config window_opacity on;
yabai -m config active_window_opacity 1.00;
yabai -m config normal_window_opacity 0.90;
yabai -m config window_opacity_duration 0.0;
yabai -m config window_shadow on;
yabai -m config window_border off;
yabai -m config status_bar off;

# ##############################################################################
# Yabai window rules
# ##############################################################################

yabai -m rule --add app="^System Preferences$" manage=off;
yabai -m rule --add app="^System Information$" manage=off;
yabai -m rule --add app="^Calculator$" manage=off;
yabai -m rule --add app="^Stickies$" manage=off;
yabai -m rule --add app="^Simulator$" manage=off;
yabai -m rule --add app="^The Unarchiver$" manage=off;
yabai -m rule --add app="^Finder$" title="^(Co(py|nnect)|Move|.*Info|Pref)$" manage=off;
yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off;
yabai -m rule --add app="^(Firefox.*)$" title="^(Opening.*)$" manage=off;
yabai -m rule --add app="^Archive Utility$" manage=off;
yabai -m rule --add app="^App Store$" manage=off;
yabai -m rule --add app="^Activity Monitor$" manage=off;
yabai -m rule --add app="^Digital Colour Meter$" manage=off;
yabai -m rule --add app="^Mail$" title="^(Signatures|Accounts|Junk Mail|Fonts & Colours|Viewing|Composing|Signatures|Rules)$" manage=off;
yabai -m rule --add app="^XD$" title="^(Adobe XD)$" manage=off;
yabai -m rule --add app="^Unity Hub$" manage=off;
yabai -m rule --add app="^Unity$" title="^()$" manage=off;
yabai -m rule --add app="^(Rider|WebStorm|JetBrains.*|Android Studio)$" title="^(Welcome to.*|Preferences)$" manage=off;
yabai -m rule --add app="^VLC$" manage=off border=off;
yabai -m rule --add app="^QuickTime Player$" manage=off;
yabai -m rule --add app="^Preview$" title!="^(.*.pdf.*)$" manage=off;
yabai -m rule --add app="^(GIMP.*)$" title!="^(GNU Image Manipulation Program|.*– GIMP)$" manage=off;
yabai -m rule --add app="^Transmission$" title!="^(Transmission)$" manage=off;
yabai -m rule --add app="^balenaEtcher$" manage=off;
yabai -m rule --add app="^Docker$" title="^Software Update$" manage=off;
yabai -m rule --add app="^(PrinterProxy|Samsung C43x Series.*)$" manage=off;
