#!/bin/bash

# ##############################################################################
# bspwm configuration
# ##############################################################################

xsetroot -cursor_name left_ptr;
hdmiConnected=$(xrandr -q | grep "HDMI-2 connected" &> /dev/null; echo $?);
if [[ "$hdmiConnected" == "0" ]]; then
  bspc monitor eDP-1 -d 1 2 3 4 5;
  bspc monitor HDMI-2 -d 6 7 8 9 0;
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9 0;
fi

bspc config initial_polarity second_child;
bspc config split_ratio 0.50
bspc config top_padding 46;
bspc config bottom_padding 0;
bspc config window_gap 20;
bspc config right_padding 0;
bspc config left_padding 0;
bspc config border_width 2;
bspc config focused_border_color "#d4be98";
bspc config active_border_color "#1d2021";
bspc config normal_border_color "#1d2021";
bspc config pointer_modifier mod5; # Opt_L => mod1, Opt_R => mod5
bspc config pointer_action1 move;
bspc config pointer_action2 resize_corner;
bspc config focus_follows_pointer false;
bspc config pointer_follows_focus false;

bspc rule -a "Onboard" state=floating;
bspc rule -a "Gnome-calculator" state=floating;

pgrep -f sxhkd || sxhkd &
pgrep -f polybar || polybar mainbar &
