#!/bin/bash

# Start pulseaudio daemon
pulseaudio --daemonize

# Set natural scrolling for mouse and modifier keys
xmodmap ~/.Xmodmap

# Custom display-settings script using xrandr
bash ~/dotfiles/scripts/display-settings.sh home

# Set the solid background color
xsetroot -solid "#2d2b55"
